name: Call a reusable workflow and use its outputs

on:
  pull_request:
    types: [labeled]

jobs:
  job1:
    uses: Rg3n0v4/test-actions-repo/.github/workflows/test-reusable-workflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
